---
source: crates/ruff_linter/src/rules/flake8_pytest_style/mod.rs
---
error[PT017]: PT017.py:19:9: Found assertion on exception `e` in `except` block, use `pytest.raises()` instead

   |
17 |         something()
18 |     except Exception as e:
19 |         assert e.message, "blah blah"
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
